[package]
name = "rcore"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_prototype_lyon = "0.10"
bevy_rapier2d = { version = "0.23", features = [ "debug-render-2d" ] }

# Scripting language to develop the VM/future language bits
rhai = { version = "1.16", features = [ "sync", "f32_float" ] }

[dependencies.bevy]
version = "0.12"
default-features = false

features = [
  # Bevy functionality:
  "multi-threaded",     # Run with multithreading
  "bevy_asset",         # Assets management
  "bevy_scene",         # Scenes management
  "bevy_winit",         # Window management (cross-platform Winit backend)
  "bevy_render",        # Rendering framework core
  "bevy_core_pipeline", # Common rendering abstractions
  "bevy_gizmos",        # Support drawing debug lines and shapes
  "bevy_sprite",        # 2D (sprites) rendering
  "bevy_pbr",           # 3D (physically-based) rendering
  "bevy_text",          # Text/font rendering
  "bevy_ui",            # UI toolkit
  "animation",          # Animation support
  "tonemapping_luts",   # Support different camera Tonemapping modes (enables KTX2+zstd)
  "default_font",       # Embed a minimal default font for text/UI
  "subpixel_glyph_atlas", # Subpixel antialiasing for text/fonts

  # File formats:
  "png",    # PNG image format for simple 2D images
  "ktx2",   # Preferred format for GPU textures
  "zstd",   # ZSTD compression support in KTX2 files

  "dynamic_linking"
]
