[package]
name = "rcore"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_prototype_lyon = { git = "https://github.com/rparrett/bevy_prototype_lyon", branch = "fix-dynamic-examples" }
bevy_rapier2d = { version = "0.30", features = [ "debug-render-2d" ] }

# Dynamic state for the simple scripting
rust_dynamic = "0.48.0"

# FPS dialog
bevy_screen_diagnostics = "0.8"

[dependencies.bevy]
version = "0.16"
default-features = false

features = [
  # Bevy functionality:
  "multi_threaded",     # Run with multithreading
  "bevy_animation",     # Provides animation functionality
  "bevy_asset",         # Assets management
  "bevy_color",         # Provides shared color types and operations
  "bevy_core_pipeline", # Common rendering abstractions
  "bevy_gizmos",        # Support drawing debug lines and shapes
  "bevy_pbr",           # 3D (physically-based) rendering
  "bevy_render",        # Rendering framework core
  "bevy_scene",         # Scenes management
  "bevy_sprite",        # 2D (sprites) rendering
  "bevy_state",         # Enable built in global state machines
  "bevy_text",          # Text/font rendering
  "bevy_ui",            # UI toolkit
  "bevy_winit",         # Window management (cross-platform Winit backend)
  "bevy_window",        # Winit dep
  "animation",          # Animation support
  "tonemapping_luts",   # Support different camera Tonemapping modes (enables KTX2+zstd)
  "default_font",       # Embed a minimal default font for text/UI

  # Bevy 0.16
  "std",
  "async_executor",

  # File formats:
  "png",    # PNG image format for simple 2D images
  "ktx2",   # Preferred format for GPU textures
  "zstd",   # ZSTD compression support in KTX2 files

  "dynamic_linking"
]
