[package]
name = "rspace"
version = "0.1.0"
authors = ["Anja Berens <pharaun666@gmail.com>"]

build = "build.rs" # lalrpop, phf_codegen

[build-dependencies]
lalrpop = "0.13.1"
phf_codegen = "0.7.21"

[dependencies]
glium = "*"
rand = "*"
cgmath = "*"

# Bit twiddling
twiddle = "0.3.0"

# Add a dependency on the regex crate; this is not
# needed if you are writing your own tokenizer by
# hand (or if you are already using the regex crate)
regex = "0.2.0"

# Add a dependency on the LALRPOP runtime library:
lalrpop-util = "0.13.1"

# phf runtime library:
phf = "0.7.21"
