[package]
name = "m6809"
version = "0.1.0"
authors = ["Anja Berens <pharaun666@gmail.com>"]
edition = "2024"

[dependencies]
# Bit twiddling
twiddle = "1.1.0"
arbitrary-int = "2"
bitfield-struct = "0.11"

# Reading bits from memory
byteorder = "1.3.2"

# Parsing
nom = "8"
